trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'
    exclude:
      - docs/README.md
      - 'TicTacToeConsole/*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 2.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '*/TicTacToeCut2.Api.csproj'
        configuration: Release
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '*/TicTacToeCut2.Api.csproj'
        arguments: '--configuration Release'
    # - task: ArchiveFiles@2
    #   inputs:
    #     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)' 
    #     includeRootFolder: false
    #     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)_$(Build.BuildId).zip' 
    #     replaceExistingArchive: true
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)_$(Build.BuildId).zip"
    #     ArtifactName: $(Build.DefinitionName)
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '*/TicTacToeCut2.Api.Tests.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)'