trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - docs/*
    exclude:
      - docs/README.md
      - docs/TicTacTestLibrary/*
      - docs/TicTacToeConsole/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: '**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration Release' # Update this to match your need
